# Generated by Django 6.0.4 on 2026-04-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('location', models.CharField(default='Canada', max_length=80)),
                ('year_of_birth', models.CharField(default='1990', max_length=10)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='member', max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('preference', models.CharField(default='light', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_plan', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('liability_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('interest', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='api.plan')),
            ],
            options={
                'db_table': 'liabilities',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=255)),
                ('position', models.CharField(default='', max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='api.plan')),
            ],
            options={
                'db_table': 'incomes',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('generation_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='api.plan')),
            ],
            options={
                'db_table': 'generations',
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('financial_goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('target_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to='api.plan')),
            ],
            options={
                'db_table': 'financial_goals',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('expenditure_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='api.plan')),
            ],
            options={
                'db_table': 'expenditures',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.BigIntegerField(default=0)),
                ('roi', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.plan')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.user'),
        ),
    ]
